dataset:
  FM_key: X_scGPT
  adata_obj: ../data/nips/nips_pp_scFM_resplit.h5ad
  celltype_key: cell_type
  control_key: neg_control
  degs_key: rank_genes_groups_cov
  dose_key: dose_val
  pc_cov: type_donor
  pert_category: cov_drug_name
  perturbation_key: condition
  smiles_key: SMILES
  split_key: split2
  split_ood: true
model:
  drug_emb: ../data/drug_embeddings/fcfp4_1024_embedding_lincs_nips.parquet
  mmd_co: 0.0
  seed: 42
training:
  checkpoint_freq: 10
  max_minutes: 1000
  num_epochs: 301
  save_dir: ../model/nips/fcfp4_mmd0.0_loss0.5l1l2+0.2_256/split2/seed42
